sudo: required

language: python
python:
  - "3.7"

services:
  - docker

install:
  - pip install -r requirements.txt

script:
  - docker build -t logistics-index .
  - docker run --rm logistics-index -m pytest tests/unit -vv
  - docker run --rm logistics-index -m flake8 src
  - docker run --rm -d --name=logistics-index-web
    -p 5000:5000
    -e POSTGRES_USER=postgres
    -e POSTGRES_PASSWORD=postgres
    -e POSTGRES_HOST=postgres
    -e POSTGRES_PORT=5432
    -e POSTGRES_DB=postgres
    logistics-index
  - curl -I -f localhost:5000

after_script:
  - docker stop logistics-index-web